apiVersion: skaffold/v4beta11
kind: Config
deploy:
  kubectl:
    {}
    # manifests:
    #   - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: "tonal-history-444709-a7"
  artifacts:
    - image: us.gcr.io/tonal-history-444709-a7/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/tonal-history-444709-a7/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/tonal-history-444709-a7/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
